/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as IosPreviewRouteImport } from './routes/ios-preview'
import { Route as LockscreenRouteImport } from './routes/lockscreen'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as PostMeetingRouteImport } from './routes/post-meeting'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as ApiAgentRouteImport } from './routes/api/agent'
import { Route as ApiCalendarRouteImport } from './routes/api/calendar'
import { Route as ApiExtractRouteImport } from './routes/api/extract'
import { Route as ApiLiveStateRouteImport } from './routes/api/live-state'
import { Route as ApiSendEmailRouteImport } from './routes/api/send-email'
import { Route as ApplyFormIdRouteImport } from './routes/apply.$formId'
import { Route as MeetingsIndexRouteImport } from './routes/meetings.index'
import { Route as MeetingsIdRouteImport } from './routes/meetings.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const IosPreviewRoute = IosPreviewRouteImport.update({
  id: '/ios-preview',
  path: '/ios-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LockscreenRoute = LockscreenRouteImport.update({
  id: '/lockscreen',
  path: '/lockscreen',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const PostMeetingRoute = PostMeetingRouteImport.update({
  id: '/post-meeting',
  path: '/post-meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarRoute = ApiCalendarRouteImport.update({
  id: '/api/calendar',
  path: '/api/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractRoute = ApiExtractRouteImport.update({
  id: '/api/extract',
  path: '/api/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveStateRoute = ApiLiveStateRouteImport.update({
  id: '/api/live-state',
  path: '/api/live-state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendEmailRoute = ApiSendEmailRouteImport.update({
  id: '/api/send-email',
  path: '/api/send-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyFormIdRoute = ApplyFormIdRouteImport.update({
  id: '/apply/$formId',
  path: '/apply/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsIndexRoute = MeetingsIndexRouteImport.update({
  id: '/meetings/',
  path: '/meetings/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsIdRoute = MeetingsIdRouteImport.update({
  id: '/meetings/$id',
  path: '/meetings/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/analytics': typeof AnalyticsRoute
  '/insights': typeof InsightsRoute
  '/integrations': typeof IntegrationsRoute
  '/ios-preview': typeof IosPreviewRoute
  '/lockscreen': typeof LockscreenRoute
  '/notifications': typeof NotificationsRoute
  '/panel': typeof PanelRoute
  '/post-meeting': typeof PostMeetingRoute
  '/watch': typeof WatchRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/calendar': typeof ApiCalendarRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/live-state': typeof ApiLiveStateRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/apply/$formId': typeof ApplyFormIdRoute
  '/meetings/$id': typeof MeetingsIdRoute
  '/meetings/': typeof MeetingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/analytics': typeof AnalyticsRoute
  '/insights': typeof InsightsRoute
  '/integrations': typeof IntegrationsRoute
  '/ios-preview': typeof IosPreviewRoute
  '/lockscreen': typeof LockscreenRoute
  '/notifications': typeof NotificationsRoute
  '/panel': typeof PanelRoute
  '/post-meeting': typeof PostMeetingRoute
  '/watch': typeof WatchRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/calendar': typeof ApiCalendarRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/live-state': typeof ApiLiveStateRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/apply/$formId': typeof ApplyFormIdRoute
  '/meetings/$id': typeof MeetingsIdRoute
  '/meetings': typeof MeetingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/analytics': typeof AnalyticsRoute
  '/insights': typeof InsightsRoute
  '/integrations': typeof IntegrationsRoute
  '/ios-preview': typeof IosPreviewRoute
  '/lockscreen': typeof LockscreenRoute
  '/notifications': typeof NotificationsRoute
  '/panel': typeof PanelRoute
  '/post-meeting': typeof PostMeetingRoute
  '/watch': typeof WatchRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/calendar': typeof ApiCalendarRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/live-state': typeof ApiLiveStateRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/apply/$formId': typeof ApplyFormIdRoute
  '/meetings/$id': typeof MeetingsIdRoute
  '/meetings/': typeof MeetingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/analytics'
    | '/insights'
    | '/integrations'
    | '/ios-preview'
    | '/lockscreen'
    | '/notifications'
    | '/panel'
    | '/post-meeting'
    | '/watch'
    | '/api/agent'
    | '/api/calendar'
    | '/api/extract'
    | '/api/live-state'
    | '/api/send-email'
    | '/apply/$formId'
    | '/meetings/$id'
    | '/meetings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/analytics'
    | '/insights'
    | '/integrations'
    | '/ios-preview'
    | '/lockscreen'
    | '/notifications'
    | '/panel'
    | '/post-meeting'
    | '/watch'
    | '/api/agent'
    | '/api/calendar'
    | '/api/extract'
    | '/api/live-state'
    | '/api/send-email'
    | '/apply/$formId'
    | '/meetings/$id'
    | '/meetings'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/analytics'
    | '/insights'
    | '/integrations'
    | '/ios-preview'
    | '/lockscreen'
    | '/notifications'
    | '/panel'
    | '/post-meeting'
    | '/watch'
    | '/api/agent'
    | '/api/calendar'
    | '/api/extract'
    | '/api/live-state'
    | '/api/send-email'
    | '/apply/$formId'
    | '/meetings/$id'
    | '/meetings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  AnalyticsRoute: typeof AnalyticsRoute
  InsightsRoute: typeof InsightsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  IosPreviewRoute: typeof IosPreviewRoute
  LockscreenRoute: typeof LockscreenRoute
  NotificationsRoute: typeof NotificationsRoute
  PanelRoute: typeof PanelRoute
  PostMeetingRoute: typeof PostMeetingRoute
  WatchRoute: typeof WatchRoute
  ApiAgentRoute: typeof ApiAgentRoute
  ApiCalendarRoute: typeof ApiCalendarRoute
  ApiExtractRoute: typeof ApiExtractRoute
  ApiLiveStateRoute: typeof ApiLiveStateRoute
  ApiSendEmailRoute: typeof ApiSendEmailRoute
  ApplyFormIdRoute: typeof ApplyFormIdRoute
  MeetingsIdRoute: typeof MeetingsIdRoute
  MeetingsIndexRoute: typeof MeetingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ios-preview': {
      id: '/ios-preview'
      path: '/ios-preview'
      fullPath: '/ios-preview'
      preLoaderRoute: typeof IosPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lockscreen': {
      id: '/lockscreen'
      path: '/lockscreen'
      fullPath: '/lockscreen'
      preLoaderRoute: typeof LockscreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-meeting': {
      id: '/post-meeting'
      path: '/post-meeting'
      fullPath: '/post-meeting'
      preLoaderRoute: typeof PostMeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar': {
      id: '/api/calendar'
      path: '/api/calendar'
      fullPath: '/api/calendar'
      preLoaderRoute: typeof ApiCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract': {
      id: '/api/extract'
      path: '/api/extract'
      fullPath: '/api/extract'
      preLoaderRoute: typeof ApiExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live-state': {
      id: '/api/live-state'
      path: '/api/live-state'
      fullPath: '/api/live-state'
      preLoaderRoute: typeof ApiLiveStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-email': {
      id: '/api/send-email'
      path: '/api/send-email'
      fullPath: '/api/send-email'
      preLoaderRoute: typeof ApiSendEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$formId': {
      id: '/apply/$formId'
      path: '/apply/$formId'
      fullPath: '/apply/$formId'
      preLoaderRoute: typeof ApplyFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/': {
      id: '/meetings/'
      path: '/meetings'
      fullPath: '/meetings/'
      preLoaderRoute: typeof MeetingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/$id': {
      id: '/meetings/$id'
      path: '/meetings/$id'
      fullPath: '/meetings/$id'
      preLoaderRoute: typeof MeetingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  AnalyticsRoute: AnalyticsRoute,
  InsightsRoute: InsightsRoute,
  IntegrationsRoute: IntegrationsRoute,
  IosPreviewRoute: IosPreviewRoute,
  LockscreenRoute: LockscreenRoute,
  NotificationsRoute: NotificationsRoute,
  PanelRoute: PanelRoute,
  PostMeetingRoute: PostMeetingRoute,
  WatchRoute: WatchRoute,
  ApiAgentRoute: ApiAgentRoute,
  ApiCalendarRoute: ApiCalendarRoute,
  ApiExtractRoute: ApiExtractRoute,
  ApiLiveStateRoute: ApiLiveStateRoute,
  ApiSendEmailRoute: ApiSendEmailRoute,
  ApplyFormIdRoute: ApplyFormIdRoute,
  MeetingsIdRoute: MeetingsIdRoute,
  MeetingsIndexRoute: MeetingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
